### ISSUE TITLE
Spike: upgrade to kratos v0.9.0

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1831]
## Description
As a developer I want to know the implications of migrating to Kratos v0.9.0-alpha.2
As an ops admin I want to be able to easier update email templates. 

## Acceptance criteria

- [ ] Client + server updated to v0.9.0-alpha.2 and functionality verified
- [ ] admin path changes: implications for routing understood and tested

Timeboxed to a day.

## Additional Context

- https://github.com/ory/kratos/blob/master/CHANGELOG.md#breaking-changes-1

```
- We moved the admin API from / to admin. This is a breaking change. Please read the explanation and proceed with caution!
```

This one will require changes in the routing in http.yml, in particular accessing the admin API:

```yml
    kratos-admin:
      rule: 'PathPrefix(`/identity/ory/kratos/admin`)'
      service: 'kratos-admin'
      middlewares:
        - strip-kratos-admin-prefix
      entryPoints:
        - 'web'
```

```
- Bugfix: fixed a bug in the handling of secrets. This is a breaking change. Please read the explanation and proceed with caution!
```
