### ISSUE TITLE
Use alkemio domain as base for all configuration parameters using it

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#2066]
## Description
As an Alkemio Developer 
I would like to easily configure the application 
so that I have less overhead developing it.

## Acceptance criteria

- [ ] Routing related configuration (that is actually fixed) to be moved out of the yml file and into a RoutePaths contants file in the server. This file is then used together with the value set by the ENDPOINT_CLUSTER env var to create the relevant urls. 
- [ ] Short (markdown) technical note regarding the routing added to the server repo to detail out the key routes used
- [ ] Usage of the environment variables that will then no longer be used removed from k8s configuration and docker-compose /docker configuration

TBD - other documentation updates that are needed? Do we refer to these routes in other documentation files?

## Additional Context
Note: one of the URLs for accessing Krator needs to remain a full URL as it is then used by the server to directly connect to Kratos **within** the cluster

e.g. acc config, see `acc.alkem.io`

```yml
  AUTH_ORY_KRATOS_ISSUER: https://acc.alkem.io
  AUTH_ORY_KRATOS_PUBLIC_BASE_URL: https://acc.alkem.io/identity/ory/kratos/public
  AUTH_ORY_KRATOS_PUBLIC_BASE_URL_SERVER: https://acc.alkem.io/identity/ory/kratos/public
  REACT_APP_ALKEMIO_DOMAIN: "https://acc.alkem.io"
  IPFS_CLIENT_ENDPOINT: https://acc.alkem.io/ipfs
  ENDPOINT_CLUSTER: https://acc.alkem.io
```
