### ISSUE TITLE
Spike: Non-idempotent operational issue fix

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#5109]
## Description

As an Alkemio User
I don't want to observe weird issues with my data
so that I can use the application without errors

## Acceptance criteria

- [ ] We have chosen an architectural approach how to manage the `non-idempotent operational issue`

## Additional Context

The issue you're facing is known as the "distributed transaction problem" or "non-idempotent operation issue" in a load-balanced, horizontally scaled environment. Since your clients have retry policies, and mutations are being load-balanced to different instances, you're experiencing data corruption.

To resolve this issue, consider the following strategies:

### 1. **Sticky Sessions (Session Persistence)**

Configure Traefik to use sticky sessions, also known as session persistence or affinity. This feature directs all requests from a client to the same backend instance for a certain period. This way, mutations from the same client will be handled by the same instance, reducing the chance of data corruption.

In Traefik, you can achieve this using the `sticky` option in your ingress configuration. Here's an example:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphql-ingress
spec:
  rules:
  - host: graphql.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: graphql-service
            port:
              number: 80
  tls:
  - hosts:
    - graphql.example.com
    secretName: tls-secret
```

And then, in your `graphql-service` configuration, add the `sticky` option:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  selector:
    app: graphql
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
```

### 2. **Idempotent Mutations**

Make your mutations idempotent, meaning that making the same mutation multiple times will have the same effect as making it once. This can be achieved by implementing optimistic concurrency control, versioning, or using a transactional approach.

For example, when updating a resource, you can use a version number or a timestamp to ensure that the update is only applied if the resource hasn't changed since the client read it.

### 3. **Centralized Transaction Management**

Implement a centralized transaction management system that coordinates mutations across your instances. This can be achieved using a message queue (e.g., RabbitMQ), a transaction manager (e.g., Atomikos), or a database that supports transactions (e.g., PostgreSQL).

When a client makes a mutation, it sends a request to the transaction manager, which then coordinates the mutation across the relevant instances. If any part of the transaction fails, the transaction manager rolls back the changes.

### 4. **Distributed Locks**

Use distributed locks to synchronize access to shared resources across your instances. This can be achieved using a lock manager like Redis or ZooKeeper.

When a client makes a mutation, it acquires a lock on the resource being mutated. If another instance tries to mutate the same resource, it will be blocked until the lock is released.

### 5. **Client-side Load Balancing with Consistent Hashing**

Implement client-side load balancing with consistent hashing. This approach uses a hashing algorithm to map clients to instances, ensuring that each client is consistently directed to the same instance.

When a client makes a mutation, it uses the consistent hashing algorithm to determine which instance to send the request to. This approach requires changes to your client implementation.

### Conclusion

The best approach depends on your specific use case, performance requirements, and the complexity of your system. You may need to combine multiple strategies to achieve the desired level of consistency and data integrity.

Before implementing any solution, consider the trade-offs in terms of performance, scalability, and complexity.

## Areas that will be affected

Graphql mutations
